Problem 1

```{r}

## pch - Generates a Symbol
## lty - line type (Solid, Dashled line)
## col - Color
## Inset - Place 

sales1 <- c(12,14,16,29,30,45,19,20,16,19,34,20)
sales2 <- rpois(12,34)
par(bg="cornsilk")

plot(sales1, col="blue", type="o", ylim=c(0,100), xlab="Month", ylab="Sales" )
title(main="Sales by Month")

lines(sales2, type="o", pch=22, lty=2, col="red")
grid(nx=NA, ny=NULL)
legend("topright", inset=.05, c("Sales1","Sales2"), fill=c("blue","red"), horiz=TRUE)


```

Problem 2

```{r}

sales<-read.table(file.choose(), header=T)
sales  # to verify that data has been read
barplot(as.matrix(sales), main="Sales Data", ylab= "Total",beside=T, col=rainbow(5))


```

Problem 3 

```{r}

fn<-boxplot(sales,col=c("orange","green"))$stats


text(1.45, fn[3,2], paste("Median =", fn[3,2]), adj=0, cex=.7)
text(0.45, fn[3,1],paste("Median =", fn[3,1]), adj=0, cex=.7)
grid(nx=NA, ny=NULL)


```

Problem 4

```{r}

fb1<-read.csv(file.choose())
aapl1<-read.csv(file.choose())
par(bg="cornsilk")
plot(aapl1$Adj.Close, col="blue", type="o", ylim=c(0,400), xlab="Days", ylab="Price" )
lines(fb1$Adj.Close, type="o", pch=22, lty=2, col="red")
legend("topright", inset=.05, c("Apple","Facebook"), fill=c("blue","red"), horiz=TRUE)

```


Problem 5

```{r}

head(women)
summary(women)
plot(women)

```

```{r}

head(uspop)
plot(uspop)

```

Problem 6 

```{r}
library("ggmap")
library("maptools")
library(maps)
register_google(key = "AIzaSyBMEQodtdMh7x22Z9QwzUyIZnN-Sm541do") 
visited <- c("SFO", "Chennai", "London", "Melbourne","Lima,Peru", "Johannesbury, SA")
ll.visited <- geocode(visited)
visit.x <- ll.visited$lon
visit.y <- ll.visited$lat
map("world", fill=TRUE, col="white", bg="lightblue", ylim=c(-60, 90), mar=c(0,0,0,0))
points(visit.x,visit.y, col="red", pch=36)

```


```{r}

library("ggmap")
library("maptools")
library(maps)
visited <- c("SFO", "New York", "Buffalo", "Dallas, TX")
ll.visited <- geocode(visited)
visit.x <- ll.visited$lon
visit.y <- ll.visited$lat
map("state", fill=TRUE, col=rainbow(50), bg="lightblue", mar=c(0,0,0,0))
points(visit.x,visit.y, col="yellow", pch=36)

```

Problem 7 

```{r}

attach(mtcars)
head(mtcars)
plot(mtcars[c(1,3,4,5,6)], main="MTCARS Data")
plot(mtcars[c(1,3,4,6)], main="MTCARS Data")
plot(mtcars[c(1,3,4,6)], col=rainbow(5),main="MTCARS Data")


```



```{r}

head(WWWusage)
plot(WWWusage,type="o",col="blue",xlab="Minute",ylab="No. of Visitors",main="No. of Visitors to the Serve \n by Each Minute")
```

Problem 8

```{r}

library(ggplot2)
ggplot(mtcars, aes(x=mpg, y=disp)) + geom_point()

ggplot(mtcars, mapping = aes(x = disp, y = mpg)) + geom_point() + 
  stat_smooth(method = 'lm')

ggplot(mtcars, mapping = aes(x = disp, y = mpg, color = as.factor(cyl))) + geom_point()
```

